spring:
  application:
    name: MediLinkSpring
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_URI}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.example.medilinkspring: DEBUG
